/**
 * Bible data loading utilities
 * This file is AUTO-GENERATED by scripts/integrate-books.ts
 * Do not edit manually - changes will be overwritten
 */

import { BibleBookData } from '@/types/bible';
import genesisData from '@/data/bible/hebrew/genesis.json';
import exodusData from '@/data/bible/hebrew/exodus.json';
import leviticusData from '@/data/bible/hebrew/leviticus.json';
import numbersData from '@/data/bible/hebrew/numbers.json';
import deuteronomyData from '@/data/bible/hebrew/deuteronomy.json';
import joshuaData from '@/data/bible/hebrew/joshua.json';
import judgesData from '@/data/bible/hebrew/judges.json';
import _1_samuelData from '@/data/bible/hebrew/1-samuel.json';
import _2_samuelData from '@/data/bible/hebrew/2-samuel.json';
import _1_kingsData from '@/data/bible/hebrew/1-kings.json';
import _2_kingsData from '@/data/bible/hebrew/2-kings.json';
import isaiahData from '@/data/bible/hebrew/isaiah.json';
import jeremiahData from '@/data/bible/hebrew/jeremiah.json';
import ezekielData from '@/data/bible/hebrew/ezekiel.json';
import hoseaData from '@/data/bible/hebrew/hosea.json';
import joelData from '@/data/bible/hebrew/joel.json';
import amosData from '@/data/bible/hebrew/amos.json';
import obadiahData from '@/data/bible/hebrew/obadiah.json';
import jonahData from '@/data/bible/hebrew/jonah.json';
import micahData from '@/data/bible/hebrew/micah.json';
import nahumData from '@/data/bible/hebrew/nahum.json';
import habakkukData from '@/data/bible/hebrew/habakkuk.json';
import zephaniahData from '@/data/bible/hebrew/zephaniah.json';
import haggaiData from '@/data/bible/hebrew/haggai.json';
import zechariahData from '@/data/bible/hebrew/zechariah.json';
import malachiData from '@/data/bible/hebrew/malachi.json';
import psalmsData from '@/data/bible/hebrew/psalms.json';
import proverbsData from '@/data/bible/hebrew/proverbs.json';
import jobData from '@/data/bible/hebrew/job.json';
import song_of_songsData from '@/data/bible/hebrew/song-of-songs.json';
import ruthData from '@/data/bible/hebrew/ruth.json';
import lamentationsData from '@/data/bible/hebrew/lamentations.json';
import ecclesiastesData from '@/data/bible/hebrew/ecclesiastes.json';
import estherData from '@/data/bible/hebrew/esther.json';
import danielData from '@/data/bible/hebrew/daniel.json';
import ezraData from '@/data/bible/hebrew/ezra.json';
import nehemiahData from '@/data/bible/hebrew/nehemiah.json';
import _1_chroniclesData from '@/data/bible/hebrew/1-chronicles.json';
import _2_chroniclesData from '@/data/bible/hebrew/2-chronicles.json';
import matthewData from '@/data/bible/greek/matthew.json';
import markData from '@/data/bible/greek/mark.json';
import lukeData from '@/data/bible/greek/luke.json';
import johnData from '@/data/bible/greek/john.json';
import actsData from '@/data/bible/greek/acts.json';
import romansData from '@/data/bible/greek/romans.json';
import _1_corinthiansData from '@/data/bible/greek/1-corinthians.json';
import _2_corinthiansData from '@/data/bible/greek/2-corinthians.json';
import galatiansData from '@/data/bible/greek/galatians.json';
import ephesiansData from '@/data/bible/greek/ephesians.json';
import philippiansData from '@/data/bible/greek/philippians.json';
import colossiansData from '@/data/bible/greek/colossians.json';
import _1_thessaloniansData from '@/data/bible/greek/1-thessalonians.json';
import _2_thessaloniansData from '@/data/bible/greek/2-thessalonians.json';
import _1_timothyData from '@/data/bible/greek/1-timothy.json';
import _2_timothyData from '@/data/bible/greek/2-timothy.json';
import titusData from '@/data/bible/greek/titus.json';
import philemonData from '@/data/bible/greek/philemon.json';
import hebrewsData from '@/data/bible/greek/hebrews.json';
import jamesData from '@/data/bible/greek/james.json';
import _1_peterData from '@/data/bible/greek/1-peter.json';
import _2_peterData from '@/data/bible/greek/2-peter.json';
import _1_johnData from '@/data/bible/greek/1-john.json';
import _2_johnData from '@/data/bible/greek/2-john.json';
import _3_johnData from '@/data/bible/greek/3-john.json';
import judeData from '@/data/bible/greek/jude.json';
import revelationData from '@/data/bible/greek/revelation.json';

/**
 * Load a Bible book's data
 */
export async function loadBook(bookId: string): Promise<BibleBookData> {
  switch (bookId) {
    case 'genesis':
      return genesisData as BibleBookData;
    case 'exodus':
      return exodusData as BibleBookData;
    case 'leviticus':
      return leviticusData as BibleBookData;
    case 'numbers':
      return numbersData as BibleBookData;
    case 'deuteronomy':
      return deuteronomyData as BibleBookData;
    case 'joshua':
      return joshuaData as BibleBookData;
    case 'judges':
      return judgesData as BibleBookData;
    case '1-samuel':
      return _1_samuelData as BibleBookData;
    case '2-samuel':
      return _2_samuelData as BibleBookData;
    case '1-kings':
      return _1_kingsData as BibleBookData;
    case '2-kings':
      return _2_kingsData as BibleBookData;
    case 'isaiah':
      return isaiahData as BibleBookData;
    case 'jeremiah':
      return jeremiahData as BibleBookData;
    case 'ezekiel':
      return ezekielData as BibleBookData;
    case 'hosea':
      return hoseaData as BibleBookData;
    case 'joel':
      return joelData as BibleBookData;
    case 'amos':
      return amosData as BibleBookData;
    case 'obadiah':
      return obadiahData as BibleBookData;
    case 'jonah':
      return jonahData as BibleBookData;
    case 'micah':
      return micahData as BibleBookData;
    case 'nahum':
      return nahumData as BibleBookData;
    case 'habakkuk':
      return habakkukData as BibleBookData;
    case 'zephaniah':
      return zephaniahData as BibleBookData;
    case 'haggai':
      return haggaiData as BibleBookData;
    case 'zechariah':
      return zechariahData as BibleBookData;
    case 'malachi':
      return malachiData as BibleBookData;
    case 'psalms':
      return psalmsData as BibleBookData;
    case 'proverbs':
      return proverbsData as BibleBookData;
    case 'job':
      return jobData as BibleBookData;
    case 'song-of-songs':
      return song_of_songsData as BibleBookData;
    case 'ruth':
      return ruthData as BibleBookData;
    case 'lamentations':
      return lamentationsData as BibleBookData;
    case 'ecclesiastes':
      return ecclesiastesData as BibleBookData;
    case 'esther':
      return estherData as BibleBookData;
    case 'daniel':
      return danielData as BibleBookData;
    case 'ezra':
      return ezraData as BibleBookData;
    case 'nehemiah':
      return nehemiahData as BibleBookData;
    case '1-chronicles':
      return _1_chroniclesData as BibleBookData;
    case '2-chronicles':
      return _2_chroniclesData as BibleBookData;
    case 'matthew':
      return matthewData as BibleBookData;
    case 'mark':
      return markData as BibleBookData;
    case 'luke':
      return lukeData as BibleBookData;
    case 'john':
      return johnData as BibleBookData;
    case 'acts':
      return actsData as BibleBookData;
    case 'romans':
      return romansData as BibleBookData;
    case '1-corinthians':
      return _1_corinthiansData as BibleBookData;
    case '2-corinthians':
      return _2_corinthiansData as BibleBookData;
    case 'galatians':
      return galatiansData as BibleBookData;
    case 'ephesians':
      return ephesiansData as BibleBookData;
    case 'philippians':
      return philippiansData as BibleBookData;
    case 'colossians':
      return colossiansData as BibleBookData;
    case '1-thessalonians':
      return _1_thessaloniansData as BibleBookData;
    case '2-thessalonians':
      return _2_thessaloniansData as BibleBookData;
    case '1-timothy':
      return _1_timothyData as BibleBookData;
    case '2-timothy':
      return _2_timothyData as BibleBookData;
    case 'titus':
      return titusData as BibleBookData;
    case 'philemon':
      return philemonData as BibleBookData;
    case 'hebrews':
      return hebrewsData as BibleBookData;
    case 'james':
      return jamesData as BibleBookData;
    case '1-peter':
      return _1_peterData as BibleBookData;
    case '2-peter':
      return _2_peterData as BibleBookData;
    case '1-john':
      return _1_johnData as BibleBookData;
    case '2-john':
      return _2_johnData as BibleBookData;
    case '3-john':
      return _3_johnData as BibleBookData;
    case 'jude':
      return judeData as BibleBookData;
    case 'revelation':
      return revelationData as BibleBookData;
    default:
      throw new Error(`Book not found: ${bookId}. Available books: genesis, exodus, leviticus, numbers, deuteronomy, joshua, judges, 1-samuel, 2-samuel, 1-kings, 2-kings, isaiah, jeremiah, ezekiel, hosea, joel, amos, obadiah, jonah, micah, nahum, habakkuk, zephaniah, haggai, zechariah, malachi, psalms, proverbs, job, song-of-songs, ruth, lamentations, ecclesiastes, esther, daniel, ezra, nehemiah, 1-chronicles, 2-chronicles, matthew, mark, luke, john, acts, romans, 1-corinthians, 2-corinthians, galatians, ephesians, philippians, colossians, 1-thessalonians, 2-thessalonians, 1-timothy, 2-timothy, titus, philemon, hebrews, james, 1-peter, 2-peter, 1-john, 2-john, 3-john, jude, revelation`);
  }
}

/**
 * Get a specific chapter from a book
 */
export function getChapter(book: BibleBookData, chapter: number) {
  const chapterData = book.chapters.find(c => c.chapter === chapter);
  if (!chapterData) {
    throw new Error(`Chapter ${chapter} not found in ${book.book.nameEnglish}`);
  }
  return chapterData;
}

/**
 * Get the text of a specific chapter
 */
export function getChapterText(book: BibleBookData, chapter: number): string {
  const chapterData = book.chapters.find(c => c.chapter === chapter);
  if (!chapterData) {
    throw new Error(`Chapter ${chapter} not found in ${book.book.nameEnglish}`);
  }
  
  // Join all verses with a space
  return chapterData.verses.map(v => v.text).join(' ');
}

/**
 * Get the text of a specific verse
 */
export function getVerseText(
  book: BibleBookData, 
  chapter: number, 
  verse: number
): string {
  const chapterData = book.chapters.find(c => c.chapter === chapter);
  if (!chapterData) {
    throw new Error(`Chapter ${chapter} not found`);
  }
  
  const verseData = chapterData.verses.find(v => v.verse === verse);
  if (!verseData) {
    throw new Error(`Verse ${chapter}:${verse} not found`);
  }
  
  return verseData.text;
}

/**
 * Get all verses in a chapter as an array
 */
export function getChapterVerses(book: BibleBookData, chapter: number) {
  const chapterData = book.chapters.find(c => c.chapter === chapter);
  if (!chapterData) {
    throw new Error(`Chapter ${chapter} not found`);
  }
  
  return chapterData.verses;
}

/**
 * Check if a book has a specific chapter
 */
export function hasChapter(book: BibleBookData, chapter: number): boolean {
  return book.chapters.some(c => c.chapter === chapter);
}

/**
 * Get the total number of verses in a chapter
 */
export function getChapterVerseCount(book: BibleBookData, chapter: number): number {
  const chapterData = book.chapters.find(c => c.chapter === chapter);
  return chapterData?.verses.length || 0;
}
