/**
 * Bible books metadata
 * This file is AUTO-GENERATED by scripts/integrate-books.ts
 * Do not edit manually - changes will be overwritten
 * 
 * To add new books, edit scripts/book-config.ts and run: npm run integrate-books
 */

import { BibleBook } from '@/types/bible';

export const BIBLE_BOOKS: BibleBook[] = [
  {
    id: 'genesis',
    name: 'בראשית',
    nameEnglish: 'Genesis',
    testament: 'tanakh',
    order: 1,
    totalChapters: 50,
    abbreviation: 'Gen'
  },
  {
    id: 'exodus',
    name: 'שמות',
    nameEnglish: 'Exodus',
    testament: 'tanakh',
    order: 2,
    totalChapters: 40,
    abbreviation: 'Exod'
  },
  {
    id: 'leviticus',
    name: 'ויקרא',
    nameEnglish: 'Leviticus',
    testament: 'tanakh',
    order: 3,
    totalChapters: 27,
    abbreviation: 'Lev'
  },
  {
    id: 'numbers',
    name: 'במדבר',
    nameEnglish: 'Numbers',
    testament: 'tanakh',
    order: 4,
    totalChapters: 36,
    abbreviation: 'Num'
  },
  {
    id: 'deuteronomy',
    name: 'דברים',
    nameEnglish: 'Deuteronomy',
    testament: 'tanakh',
    order: 5,
    totalChapters: 34,
    abbreviation: 'Deut'
  },
  {
    id: 'joshua',
    name: 'יהושע',
    nameEnglish: 'Joshua',
    testament: 'tanakh',
    order: 6,
    totalChapters: 24,
    abbreviation: 'Josh'
  },
  {
    id: 'judges',
    name: 'שופטים',
    nameEnglish: 'Judges',
    testament: 'tanakh',
    order: 7,
    totalChapters: 21,
    abbreviation: 'Judg'
  },
  {
    id: '1-samuel',
    name: 'שמואל א',
    nameEnglish: '1 Samuel',
    testament: 'tanakh',
    order: 8,
    totalChapters: 31,
    abbreviation: '1 Sam'
  },
  {
    id: '2-samuel',
    name: 'שמואל ב',
    nameEnglish: '2 Samuel',
    testament: 'tanakh',
    order: 9,
    totalChapters: 24,
    abbreviation: '2 Sam'
  },
  {
    id: '1-kings',
    name: 'מלכים א',
    nameEnglish: '1 Kings',
    testament: 'tanakh',
    order: 10,
    totalChapters: 22,
    abbreviation: '1 Kgs'
  },
  {
    id: '2-kings',
    name: 'מלכים ב',
    nameEnglish: '2 Kings',
    testament: 'tanakh',
    order: 11,
    totalChapters: 25,
    abbreviation: '2 Kgs'
  },
  {
    id: 'isaiah',
    name: 'ישעיה',
    nameEnglish: 'Isaiah',
    testament: 'tanakh',
    order: 12,
    totalChapters: 66,
    abbreviation: 'Isa'
  },
  {
    id: 'jeremiah',
    name: 'ירמיה',
    nameEnglish: 'Jeremiah',
    testament: 'tanakh',
    order: 13,
    totalChapters: 52,
    abbreviation: 'Jer'
  },
  {
    id: 'ezekiel',
    name: 'יחזקאל',
    nameEnglish: 'Ezekiel',
    testament: 'tanakh',
    order: 14,
    totalChapters: 48,
    abbreviation: 'Ezek'
  },
  {
    id: 'hosea',
    name: 'הושע',
    nameEnglish: 'Hosea',
    testament: 'tanakh',
    order: 15,
    totalChapters: 14,
    abbreviation: 'Hos'
  },
  {
    id: 'joel',
    name: 'יואל',
    nameEnglish: 'Joel',
    testament: 'tanakh',
    order: 16,
    totalChapters: 4,
    abbreviation: 'Joel'
  },
  {
    id: 'amos',
    name: 'עמוס',
    nameEnglish: 'Amos',
    testament: 'tanakh',
    order: 17,
    totalChapters: 9,
    abbreviation: 'Amos'
  },
  {
    id: 'obadiah',
    name: 'עובדיה',
    nameEnglish: 'Obadiah',
    testament: 'tanakh',
    order: 18,
    totalChapters: 1,
    abbreviation: 'Obad'
  }
];

export const BIBLE_METADATA = {
  totalBooks: BIBLE_BOOKS.length,
  availableBooks: BIBLE_BOOKS.length,
  totalChapters: BIBLE_BOOKS.reduce((sum, book) => sum + book.totalChapters, 0),
};

export const BOOK_CATEGORIES = {
  torah: {
    name: 'Torah',
    hebrewName: 'תורה',
    books: BIBLE_BOOKS.filter(b => b.order <= 5).map(b => b.id)
  },
  prophets: {
    name: 'Prophets',
    hebrewName: 'נביאים',
    books: BIBLE_BOOKS.filter(b => b.order >= 6 && b.order <= 26).map(b => b.id)
  },
  writings: {
    name: 'Writings',
    hebrewName: 'כתובים',
    books: BIBLE_BOOKS.filter(b => b.order >= 27).map(b => b.id)
  }
};
