/**
 * Bible books metadata
 * This file is AUTO-GENERATED by scripts/integrate-books.ts
 * Do not edit manually - changes will be overwritten
 * 
 * To add new books, edit scripts/book-config.ts and run: npm run integrate-books
 */

import { BibleBook } from '@/types/bible';

export const BIBLE_BOOKS: BibleBook[] = [
  {
    id: 'genesis',
    name: 'בראשית',
    nameEnglish: 'Genesis',
    testament: 'tanakh',
    order: 1,
    totalChapters: 50,
    abbreviation: 'Gen'
  },
  {
    id: 'exodus',
    name: 'שמות',
    nameEnglish: 'Exodus',
    testament: 'tanakh',
    order: 2,
    totalChapters: 40,
    abbreviation: 'Exod'
  },
  {
    id: 'leviticus',
    name: 'ויקרא',
    nameEnglish: 'Leviticus',
    testament: 'tanakh',
    order: 3,
    totalChapters: 27,
    abbreviation: 'Lev'
  },
  {
    id: 'numbers',
    name: 'במדבר',
    nameEnglish: 'Numbers',
    testament: 'tanakh',
    order: 4,
    totalChapters: 36,
    abbreviation: 'Num'
  },
  {
    id: 'deuteronomy',
    name: 'דברים',
    nameEnglish: 'Deuteronomy',
    testament: 'tanakh',
    order: 5,
    totalChapters: 34,
    abbreviation: 'Deut'
  },
  {
    id: 'joshua',
    name: 'יהושע',
    nameEnglish: 'Joshua',
    testament: 'tanakh',
    order: 6,
    totalChapters: 24,
    abbreviation: 'Josh'
  },
  {
    id: 'judges',
    name: 'שופטים',
    nameEnglish: 'Judges',
    testament: 'tanakh',
    order: 7,
    totalChapters: 21,
    abbreviation: 'Judg'
  },
  {
    id: '1-samuel',
    name: 'שמואל א',
    nameEnglish: '1 Samuel',
    testament: 'tanakh',
    order: 8,
    totalChapters: 31,
    abbreviation: '1 Sam'
  },
  {
    id: '2-samuel',
    name: 'שמואל ב',
    nameEnglish: '2 Samuel',
    testament: 'tanakh',
    order: 9,
    totalChapters: 24,
    abbreviation: '2 Sam'
  },
  {
    id: '1-kings',
    name: 'מלכים א',
    nameEnglish: '1 Kings',
    testament: 'tanakh',
    order: 10,
    totalChapters: 22,
    abbreviation: '1 Kgs'
  },
  {
    id: '2-kings',
    name: 'מלכים ב',
    nameEnglish: '2 Kings',
    testament: 'tanakh',
    order: 11,
    totalChapters: 25,
    abbreviation: '2 Kgs'
  },
  {
    id: 'isaiah',
    name: 'ישעיה',
    nameEnglish: 'Isaiah',
    testament: 'tanakh',
    order: 12,
    totalChapters: 66,
    abbreviation: 'Isa'
  },
  {
    id: 'jeremiah',
    name: 'ירמיה',
    nameEnglish: 'Jeremiah',
    testament: 'tanakh',
    order: 13,
    totalChapters: 52,
    abbreviation: 'Jer'
  },
  {
    id: 'ezekiel',
    name: 'יחזקאל',
    nameEnglish: 'Ezekiel',
    testament: 'tanakh',
    order: 14,
    totalChapters: 48,
    abbreviation: 'Ezek'
  },
  {
    id: 'hosea',
    name: 'הושע',
    nameEnglish: 'Hosea',
    testament: 'tanakh',
    order: 15,
    totalChapters: 14,
    abbreviation: 'Hos'
  },
  {
    id: 'joel',
    name: 'יואל',
    nameEnglish: 'Joel',
    testament: 'tanakh',
    order: 16,
    totalChapters: 4,
    abbreviation: 'Joel'
  },
  {
    id: 'amos',
    name: 'עמוס',
    nameEnglish: 'Amos',
    testament: 'tanakh',
    order: 17,
    totalChapters: 9,
    abbreviation: 'Amos'
  },
  {
    id: 'obadiah',
    name: 'עובדיה',
    nameEnglish: 'Obadiah',
    testament: 'tanakh',
    order: 18,
    totalChapters: 1,
    abbreviation: 'Obad'
  },
  {
    id: 'jonah',
    name: 'יונה',
    nameEnglish: 'Jonah',
    testament: 'tanakh',
    order: 19,
    totalChapters: 4,
    abbreviation: 'Jonah'
  },
  {
    id: 'micah',
    name: 'מיכה',
    nameEnglish: 'Micah',
    testament: 'tanakh',
    order: 20,
    totalChapters: 7,
    abbreviation: 'Mic'
  },
  {
    id: 'nahum',
    name: 'נחום',
    nameEnglish: 'Nahum',
    testament: 'tanakh',
    order: 21,
    totalChapters: 3,
    abbreviation: 'Nah'
  },
  {
    id: 'habakkuk',
    name: 'חבקוק',
    nameEnglish: 'Habakkuk',
    testament: 'tanakh',
    order: 22,
    totalChapters: 3,
    abbreviation: 'Hab'
  },
  {
    id: 'zephaniah',
    name: 'צפניה',
    nameEnglish: 'Zephaniah',
    testament: 'tanakh',
    order: 23,
    totalChapters: 3,
    abbreviation: 'Zeph'
  },
  {
    id: 'haggai',
    name: 'חגי',
    nameEnglish: 'Haggai',
    testament: 'tanakh',
    order: 24,
    totalChapters: 2,
    abbreviation: 'Hag'
  },
  {
    id: 'zechariah',
    name: 'זכריה',
    nameEnglish: 'Zechariah',
    testament: 'tanakh',
    order: 25,
    totalChapters: 14,
    abbreviation: 'Zech'
  },
  {
    id: 'malachi',
    name: 'מלאכי',
    nameEnglish: 'Malachi',
    testament: 'tanakh',
    order: 26,
    totalChapters: 3,
    abbreviation: 'Mal'
  },
  {
    id: 'psalms',
    name: 'תהלים',
    nameEnglish: 'Psalms',
    testament: 'tanakh',
    order: 27,
    totalChapters: 150,
    abbreviation: 'Ps'
  },
  {
    id: 'proverbs',
    name: 'משלי',
    nameEnglish: 'Proverbs',
    testament: 'tanakh',
    order: 28,
    totalChapters: 31,
    abbreviation: 'Prov'
  },
  {
    id: 'job',
    name: 'איוב',
    nameEnglish: 'Job',
    testament: 'tanakh',
    order: 29,
    totalChapters: 42,
    abbreviation: 'Job'
  },
  {
    id: 'song-of-songs',
    name: 'שיר השירים',
    nameEnglish: 'Song of Songs',
    testament: 'tanakh',
    order: 30,
    totalChapters: 8,
    abbreviation: 'Song'
  },
  {
    id: 'ruth',
    name: 'רות',
    nameEnglish: 'Ruth',
    testament: 'tanakh',
    order: 31,
    totalChapters: 4,
    abbreviation: 'Ruth'
  },
  {
    id: 'lamentations',
    name: 'איכה',
    nameEnglish: 'Lamentations',
    testament: 'tanakh',
    order: 32,
    totalChapters: 5,
    abbreviation: 'Lam'
  },
  {
    id: 'ecclesiastes',
    name: 'קהלת',
    nameEnglish: 'Ecclesiastes',
    testament: 'tanakh',
    order: 33,
    totalChapters: 12,
    abbreviation: 'Eccl'
  },
  {
    id: 'esther',
    name: 'אסתר',
    nameEnglish: 'Esther',
    testament: 'tanakh',
    order: 34,
    totalChapters: 10,
    abbreviation: 'Esth'
  },
  {
    id: 'daniel',
    name: 'דניאל',
    nameEnglish: 'Daniel',
    testament: 'tanakh',
    order: 35,
    totalChapters: 12,
    abbreviation: 'Dan'
  },
  {
    id: 'ezra',
    name: 'עזרא',
    nameEnglish: 'Ezra',
    testament: 'tanakh',
    order: 36,
    totalChapters: 10,
    abbreviation: 'Ezra'
  },
  {
    id: 'nehemiah',
    name: 'נחמיה',
    nameEnglish: 'Nehemiah',
    testament: 'tanakh',
    order: 37,
    totalChapters: 13,
    abbreviation: 'Neh'
  },
  {
    id: '1-chronicles',
    name: 'דברי הימים א',
    nameEnglish: '1 Chronicles',
    testament: 'tanakh',
    order: 38,
    totalChapters: 29,
    abbreviation: '1Chr'
  },
  {
    id: '2-chronicles',
    name: 'דברי הימים ב',
    nameEnglish: '2 Chronicles',
    testament: 'tanakh',
    order: 39,
    totalChapters: 36,
    abbreviation: '2Chr'
  },
  {
    id: 'matthew',
    name: 'ΚΑΤΑ ΜΑΘΘΑΙΟΝ',
    nameEnglish: 'Matthew',
    testament: 'new-testament',
    order: 40,
    totalChapters: 28,
    abbreviation: 'Matt'
  },
  {
    id: 'mark',
    name: 'ΚΑΤΑ ΜΑΡΚΟΝ',
    nameEnglish: 'Mark',
    testament: 'new-testament',
    order: 41,
    totalChapters: 16,
    abbreviation: 'Mark'
  },
  {
    id: 'luke',
    name: 'ΚΑΤΑ ΛΟΥΚΑΝ',
    nameEnglish: 'Luke',
    testament: 'new-testament',
    order: 42,
    totalChapters: 24,
    abbreviation: 'Luke'
  },
  {
    id: 'john',
    name: 'ΚΑΤΑ ΙΩΑΝΝΗΝ',
    nameEnglish: 'John',
    testament: 'new-testament',
    order: 43,
    totalChapters: 21,
    abbreviation: 'John'
  },
  {
    id: 'acts',
    name: 'ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ',
    nameEnglish: 'Acts',
    testament: 'new-testament',
    order: 44,
    totalChapters: 28,
    abbreviation: 'Acts'
  },
  {
    id: 'romans',
    name: 'ΠΡΟΣ ΡΩΜΑΙΟΥΣ',
    nameEnglish: 'Romans',
    testament: 'new-testament',
    order: 45,
    totalChapters: 16,
    abbreviation: 'Rom'
  },
  {
    id: '1-corinthians',
    name: 'ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Α',
    nameEnglish: '1 Corinthians',
    testament: 'new-testament',
    order: 46,
    totalChapters: 16,
    abbreviation: '1Cor'
  },
  {
    id: '2-corinthians',
    name: 'ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β',
    nameEnglish: '2 Corinthians',
    testament: 'new-testament',
    order: 47,
    totalChapters: 13,
    abbreviation: '2Cor'
  },
  {
    id: 'galatians',
    name: 'ΠΡΟΣ ΓΑΛΑΤΑΣ',
    nameEnglish: 'Galatians',
    testament: 'new-testament',
    order: 48,
    totalChapters: 6,
    abbreviation: 'Gal'
  },
  {
    id: 'ephesians',
    name: 'ΠΡΟΣ ΕΦΕΣΙΟΥΣ',
    nameEnglish: 'Ephesians',
    testament: 'new-testament',
    order: 49,
    totalChapters: 6,
    abbreviation: 'Eph'
  },
  {
    id: 'philippians',
    name: 'ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ',
    nameEnglish: 'Philippians',
    testament: 'new-testament',
    order: 50,
    totalChapters: 4,
    abbreviation: 'Phil'
  },
  {
    id: 'colossians',
    name: 'ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ',
    nameEnglish: 'Colossians',
    testament: 'new-testament',
    order: 51,
    totalChapters: 4,
    abbreviation: 'Col'
  },
  {
    id: '1-thessalonians',
    name: 'ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α',
    nameEnglish: '1 Thessalonians',
    testament: 'new-testament',
    order: 52,
    totalChapters: 5,
    abbreviation: '1Thess'
  },
  {
    id: '2-thessalonians',
    name: 'ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β',
    nameEnglish: '2 Thessalonians',
    testament: 'new-testament',
    order: 53,
    totalChapters: 3,
    abbreviation: '2Thess'
  },
  {
    id: '1-timothy',
    name: 'ΠΡΟΣ ΤΙΜΟΘΕΟΝ Α',
    nameEnglish: '1 Timothy',
    testament: 'new-testament',
    order: 54,
    totalChapters: 6,
    abbreviation: '1Tim'
  },
  {
    id: '2-timothy',
    name: 'ΠΡΟΣ ΤΙΜΟΘΕΟΝ Β',
    nameEnglish: '2 Timothy',
    testament: 'new-testament',
    order: 55,
    totalChapters: 4,
    abbreviation: '2Tim'
  },
  {
    id: 'titus',
    name: 'ΠΡΟΣ ΤΙΤΟΝ',
    nameEnglish: 'Titus',
    testament: 'new-testament',
    order: 56,
    totalChapters: 3,
    abbreviation: 'Titus'
  },
  {
    id: 'philemon',
    name: 'ΠΡΟΣ ΦΙΛΗΜΟΝΑ',
    nameEnglish: 'Philemon',
    testament: 'new-testament',
    order: 57,
    totalChapters: 1,
    abbreviation: 'Phlm'
  },
  {
    id: 'hebrews',
    name: 'ΠΡΟΣ ΕΒΡΑΙΟΥΣ',
    nameEnglish: 'Hebrews',
    testament: 'new-testament',
    order: 58,
    totalChapters: 13,
    abbreviation: 'Heb'
  },
  {
    id: 'james',
    name: 'ΙΑΚΩΒΟΥ',
    nameEnglish: 'James',
    testament: 'new-testament',
    order: 59,
    totalChapters: 5,
    abbreviation: 'Jas'
  },
  {
    id: '1-peter',
    name: 'ΠΕΤΡΟΥ Α',
    nameEnglish: '1 Peter',
    testament: 'new-testament',
    order: 60,
    totalChapters: 5,
    abbreviation: '1Pet'
  },
  {
    id: '2-peter',
    name: 'ΠΕΤΡΟΥ Β',
    nameEnglish: '2 Peter',
    testament: 'new-testament',
    order: 61,
    totalChapters: 3,
    abbreviation: '2Pet'
  },
  {
    id: '1-john',
    name: 'ΙΩΑΝΝΟΥ Α',
    nameEnglish: '1 John',
    testament: 'new-testament',
    order: 62,
    totalChapters: 5,
    abbreviation: '1John'
  },
  {
    id: '2-john',
    name: 'ΙΩΑΝΝΟΥ Β',
    nameEnglish: '2 John',
    testament: 'new-testament',
    order: 63,
    totalChapters: 1,
    abbreviation: '2John'
  },
  {
    id: '3-john',
    name: 'ΙΩΑΝΝΟΥ Γ',
    nameEnglish: '3 John',
    testament: 'new-testament',
    order: 64,
    totalChapters: 1,
    abbreviation: '3John'
  },
  {
    id: 'jude',
    name: 'ΙΟΥΔΑ',
    nameEnglish: 'Jude',
    testament: 'new-testament',
    order: 65,
    totalChapters: 1,
    abbreviation: 'Jude'
  },
  {
    id: 'revelation',
    name: 'ΑΠΟΚΑΛΥΨΙΣ ΙΩΑΝΝΟΥ',
    nameEnglish: 'Revelation',
    testament: 'new-testament',
    order: 66,
    totalChapters: 22,
    abbreviation: 'Rev'
  }
];

export const BIBLE_METADATA = {
  totalBooks: BIBLE_BOOKS.length,
  availableBooks: BIBLE_BOOKS.length,
  totalChapters: BIBLE_BOOKS.reduce((sum, book) => sum + book.totalChapters, 0),
};

export const BOOK_CATEGORIES = {
  torah: {
    name: 'Torah',
    hebrewName: 'תורה',
    books: BIBLE_BOOKS.filter(b => b.order <= 5).map(b => b.id)
  },
  prophets: {
    name: 'Prophets',
    hebrewName: 'נביאים',
    books: BIBLE_BOOKS.filter(b => b.order >= 6 && b.order <= 26).map(b => b.id)
  },
  writings: {
    name: 'Writings',
    hebrewName: 'כתובים',
    books: BIBLE_BOOKS.filter(b => b.order >= 27 && b.order <= 39).map(b => b.id)
  },
  'new-testament': {
    name: 'New Testament',
    hebrewName: 'הברית החדשה',
    books: BIBLE_BOOKS.filter(b => b.order >= 40).map(b => b.id)
  }
};
